### PR TITLE
Gustavo branch2

### PR DESCRIPTION
**Pull request by gareyes3**
Eric this is the fix for the buttons. I had to create a new branch because my original branch was not syncing from Master. I will use this one from now on

### CODE REVIEW

**Comment by ericxbcheng** [comment]
Hey Gustavo, really nice job on the buttons!! One thing I'd recommend is that you could try wrapping the action buttons with a fluidRow(), like what I did for the dimension input boxes in ui.R. Because when I ran the GUI in browser, I noticed that some of the buttons are not positioned right after the input box, like in this screenshot.

image

Here is how I would write it. 

fluidRow(
    column(width = 10, #here you can copy my code for the input boxes# ),
    column(width = 2, #here you put the action button#)
)

**Comment by gareyes3** [comment]
Sounds good!


Gustavo Reyes
Research Assistant, M.S Student

Department of Food Science and Human Nutrition
University of Illinois Urbana-Champaign
110 Agricultural Bioprocess Laboratory
1302 W Pennsylvania Ave. Urbana, IL 61801
gareyes3@illinois.edu<mailto:gareyes3@illinois.edu>
[Illinois-Wordmark-Horizontal-Full-Color-RGB]

**Comment by gareyes3** [comment]
Eric I fixed the buttons. they should be good. Now I will focus on finishing the Documentation content

**Comment by ericxbcheng** [comment]
Gustavo great job!!! Thank you so much for fixing all the buttons. 

Here I attached a figure that visualizes how the homogeneity may change the distribution of the aflatoxin concentration in the final sample. Feel free to put this in the documentation.

image

**Pull request merged**
